### ISSUE TITLE
SyncStatesThree.yml is not working

### ISSUE THREAD

**Issue by rodrigoscoelho** [johanschelin/ha_blueprint_windowsopenalert#1]
It's impossible to use SyncStatesThree.yml

After saving, Home assistant is not showing it as a automation.

**Comment by johanschelin** [comment]
Can you see any errors in the log under Configuration Logs? Errors from blueprint-created Automations should be logged there. Try Reloading Automations or rebooting HA to trigger the error to be logged. I probably can help fix the error if I can see the error-log.

**Comment by johanschelin** [comment]
Have you filled in all three entity names? If you only fill in two, the automation will not be created succesfylly.

**Comment by rodrigoscoelho** [comment]
Yes, used both 3.

Em seg., 12 de abr. de 2021 às 18:17, johanschelin ***@***.***>
escreveu:

**Comment by johanschelin** [comment]
Can you see any errors in the log under Configuration Logs? Errors from blueprint-created Automations should be logged there. Try Reloading Automations or rebooting HA to trigger the error to be logged. I probably can help fix the error if I can see the error-log.
I tested the blueprint in my setup again and republished the code. So please delete and re-download the blueprint and come back with error-logs.
