### ISSUE TITLE
Blueprint file There is a YML error unknown tag but I don’t know how to solve it

### ISSUE THREAD

**Issue by love768952693** [johanschelin/ha_blueprint_windowsopenalert#2]
`unknown tag !<!input> at line 35, column 30:
      switch_1: !input 'switch_1'
                                 ^`

**Comment by johanschelin** [comment]
Hi!
Which blueprint file are you refering to? Does the error arise in the HA log or where?

**Comment by love768952693** [comment]
I installed the `configurator` suite. With it, I can directly edit YML files in homeassistant.

In addition, if you directly use the YML editing tool, this prompt will also appear.

I'm not sure what the reason is, or the syntax is incorrect, although the blueprint works.

**Comment by johanschelin** [comment]
If something "tests the code" - it will probably give an error as you havent provided any inputs - so the tester does not know what !input does mean. It has no variables if you dont create and run the automation. You can't test the Blueprint code.
