### ISSUE TITLE
2 entity option but uses elif

### ISSUE THREAD

**Issue by ruddj** [johanschelin/ha_blueprint_windowsopenalert#4]
Good Day,
 I was wondering why you have an if/elif/else statement for the 2 state sync rather than just an if / else? Is this leftover from converting from 3 state or does it do something outside the visible logic?

https://github.com/johanschelin/ha_blueprints/blob/e6aa68b109d1cee8f5607e419433c5c25f6bc2f6/SyncStates-2.yaml#L48

Couldn't it just be:
```
    entity_id: '{% if trigger.from_state.entity_id == switch_1 %} {{ switch_2 }} 
      {% else %} {{ switch_1 }} {% endif %}'
```

Also comment at top of file says "Bind **three** entities together"

**Comment by johanschelin** [comment]
Hi @ruddj - that is correct. This is a variant of the Three States Sync where I just changed the code. It can certainly be modified with our suggestion - which now is done! :)
